### ISSUE TITLE
Please test 1.0.0-beta1

### ISSUE THREAD

**Issue by elliottslaughter** [terralang/terra#323]
CCing people who have been active recently or who have contributed to the recent release: @viluon @bananu7 @OvermindDL1 @Mx7f @ProfFan @Clyybber

I've put together a beta for the upcoming 1.0 release. If you have the time, please download it and make sure it is working. I'm particularly looking for someone to test the Windows build.

  * Binaries: https://github.com/zdevito/terra/releases/tag/release-1.0.0-beta1
  * Release notes: https://github.com/zdevito/terra/blob/master/CHANGES.md

If no major issues are found I'll release this as 1.0.

Test matrix for release:

Test/OS| Linux | OSX | Windows
--|--|--|--
Test Suite w/o CUDA| :white_check_mark: (Travis) | :white_check_mark: (Travis) | :white_check_mark: (AppVeyor)
Test Suite with CUDA| :white_check_mark: (@elliottslaughter) | :white_check_mark: (@ProfFan) |  
Rigel | :white_check_mark: (@elliottslaughter) |   |  
Opt          |    | :white_check_mark: (@ProfFan) |  
Regent | :white_check_mark: (@elliottslaughter) | :white_check_mark: (@elliottslaughter) | N/A

Other todo items:

 - [ ] #173 (document `label([name])` and `and` for multiple functions)
 - [ ] #154 (document `defer`)
 - [ ] https://github.com/zdevito/terra/issues/323#issuecomment-447613468 (CUDA slowdown)
 - [ ] #333 (document `__for`)
 - [x] #339 (document `lex:terraexpr()` and `lex:terrastats()`)
 - [x] #383 (deprecate Make)
 - [x] #403 (deprecate NMake)
 - [ ]  #366 (portability of Linux binaries)

Optional:

 - [ ] #388 (holy build box)

**Comment by OvermindDL1** [comment]
> `523 tests passed. 0 tests failed.`

Test `run` on linux.

My simple sandbox code seems to work fine too but it doesn't really stress much.  :-)

**Comment by elliottslaughter** [comment]
I think that's just saying that the argument is optional, and has a default value of `true`? (See e.g. http://terralang.org/api.html#symbol) I agree that it's confusing though, since both `[]` and `{}` are valid syntax in the language!

If you have ideas for how to make it more clear, please create a new issue---I think this will be pretty pervasive in the docs so it won't be a quick and simple change.

**Comment by ProfFan** [comment]
We could probably have a matrix of test conditions here and check them all. Also, I think it is nice to have dependent projects like `Darkroom` and `Opt` added to the test matrix.
Probably like

Test/OS| Linux | OSX | Windows
--|--|--|--
Test Suite w/o CUDA|    |   |  
Test Suite with CUDA|    |   |  
Darkroom|    |   |  
Opt          |    |    |  
etc. | | |

**Comment by elliottslaughter** [comment]
@ProfFan Ok, I copied your test matrix into the issue description up top.

Would you be willing to test Opt?

Also, do you know any contacts for Darkroom? I'm all in favor of having everyone test this, but I'm not going to know how to run their tests myself.

**Comment by elliottslaughter** [comment]
FYI, I noticed an issue where the macOS binary that got uploaded did not have CUDA enabled (due to a bug in a condition on Travis). I've renamed that binary, and re-run the correct Travis job, so the new binary should have CUDA enabled.

**Comment by bananu7** [comment]
> I'm particularly looking for someone to test the Windows build.

Well, I tried. Namely:

    terra-Windows-x86_64-2e2032e\share\terra\tests $ ..\..\..\bin\terra run
    terra-Windows-x86_64-2e2032e\bin $ terra ..\share\terra\tests\run

And copying the terra binary to the tests folder and running from there. (Neither is in the README, which I doesn't correspond to the zip folder structure). Only the first one sort of went through, producing a lot of:

    ERROR: The system was unable to find the specified registry or key value.

In the end:

     453 tests passed. 70 tests failed.

But quickly looking at the log, a good chunk of the fails was due to the fact that `stdio.h` wasn't found; should I point Terra to my VS includes somehow?

Here's the [full test log](https://github.com/zdevito/terra/files/2623634/log.txt).

**Comment by bananu7** [comment]
And oh, Darkroom tests seem to be failing because of the same issue.

**Comment by ProfFan** [comment]
@elliottslaughter I will test Opt on macOS and Linux in a few days.

**Comment by Clyybber** [comment]
@bananu7 I think darkroom relies on platform specific things, such as pthreads:
`cpthread = terralib.includec("pthread.h")`
https://github.com/jameshegarty/darkroom/blob/master/src/backend_terra.t

> Darkroom and Terra are tested to work on Linux and Mac OS X. Other platforms are unlikely to work.

**Comment by bananu7** [comment]
@Clyybber Would be worth a try to test it with MinGW `pthread`, but I didn't even get to that point anyway.

**Comment by OvermindDL1** [comment]
I grabbed a Windows 10 machine at work that has cygwin and the visual studio tools and a lot of other dev stuff that no one uses here anymore and the best I was able to get the tests to do was `453 tests passed. 70 tests failed`, though it won't really affect me as I don't use Windows.  None of my tests include cuda either as I use OpenCL and Vulkan rather than Cuda (yay standards).

Full failing list:
```zsh
=================
= FAILING tests
=================
ainline.t
arrayt.t
atoi.t
avxhadd.t
benchmark_fannkuchredux.t
benchmark_nbody.t
bf.t
blocking.t
blocking2-fixed.t
blocking2.t
blocking3.t
bounce.t
breaktest.t
bug2.t
bug4.t
cconv.t
clanginfo.t
class.t
class2.t
class3.t
class5.t
class6.t
clean.t
defer.t
deferbreak.t
defergoto.t
dgemm.t
dgemm2.t
dgemm3.t
diffuse.t
dynlib.t
exportdynamic.t
fakeasm.t
gemm.t
hello.t
hello2.t
includec.t
luaapi.t
malloc.t
mathlib.t
multiterra.t
new.t
objtest.t
option_e.t
output.t
printfarray.t
printfloat.t
proxystruct.t
quote7.t
quote8.t
quote9.t
quoteselect.t
recstruct.t
renaming.t
scc.t
sgemm-old.t
sgemm.t
sgemm3.t
sgemmkernel.t
sharedlib.t
speed.t
ssimple.t
stencil.t
strerror.t
string.t
symbolmangling.t
testminmax.t
teststd.t
testvector.t
varargcstring.t
=================

453 tests passed. 70 tests failed.
```

I tested gcc and linking with some simple C/C++ programs that used some standard headers with no issue, and likewise with the VC tools and nmake'ing a simple project.  Note that it is the Visual Studio compiler that is installed, not the full IDE, but the entire compiler pipeline and VS headers and all are installed.

**Comment by OvermindDL1** [comment]
I can test something else out if needed as well.  If needing of anything 'too' windows specific I may need help with as I'm a linux user, not a Windows user, and thus I don't know Windows quite perfectly, but I do have a bash shell and all the VS and cygwin tools available.

**Comment by bananu7** [comment]
OK, so the results from my machine are in:

    455 tests passed. 68 tests failed.

Seems that the include situation isn't really much better:

```
In file included from <buffer>:1:
In file included from C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC/INCLUDE\stdio.h:20:
C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/INCLUDE\crtdefs.h:10:10: fatal error: 'corecrt.h' file not found
#include <corecrt.h>
         ^~~~~~~~~~~

```

**Comment by bananu7** [comment]
I'm pretty sure that [this is the problematic part](https://github.com/zdevito/terra/blob/2f3f380c88dfad83de53c997508e802942a843b0/src/tcwrapper.cpp#L983-L989).

The fact that it, sort of maliciously, inserts the 14.0 path can be observed by running `clanginfo.t` test.

And indeed, disabling (temporarily changing the name of the folder) the 14.0 includes makes it work - all tests pass.

**Comment by Mx7f** [comment]
This was the relevant pull request: [https://github.com/zdevito/terra/pull/315](https://github.com/zdevito/terra/pull/315), you can see why that part was added (or rather, rearranged) in there. I hadn't gotten the bandwidth to figure out how fix it properly.

**Comment by elliottslaughter** [comment]
@bananu7 I'd love to accept a pull request for this. As you can see in the discussion of #315, I spent some time trying to figure out how to fix it, but debugging via AppVeyor builds is about the slowest debugging cycle you can possibly imagine, and I eventually gave up on it. Someone with a working Visual Studio install could probably iterate a lot faster.

I see two possible options:

 1. Rely entirely on Clang, since we've got a lot of duplication of the paths we can probably just remove our versions of them. Presumably if we're not setting up bad paths in the code I linked above, then the Clang paths will just be used if we put the code back where it was originally. (I.e. Clang paths no longer need to be forced to come first.)
 2. Fix the auto-detection of the registry keys so that we can find the correct paths ourselves, and then we can put the Clang paths back into their normal place.

**Comment by OvermindDL1** [comment]
> @OvermindDL1 For your Windows tests, what Windows and Visual Studio versions do you have installed?

2017 I think I remembered seeing?  Whatever was the latest available toolset earlier this year most likely.

> On second thoughts, why can't those headers be bundled together with Terra? Is there some licensing issue there?

Not if you use clang's headers.  :-)
There is with gcc's and VS's.

> Rely entirely on Clang, since we've got a lot of duplication of the paths we can probably just remove our versions of them. Presumably if we're not setting up bad paths in the code I linked above, then the Clang paths will just be used if we put the code back where it was originally. (I.e. Clang paths no longer need to be forced to come first.)

Honestly I'd say just do this, even Visual Studio 2017+ itself supports clang now.  You'd have to use a *very* recent clang version though.

> Fix the auto-detection of the registry keys so that we can find the correct paths ourselves, and then we can put the Clang paths back into their normal place.

For note, I'm not entirely sure that the Visual Studio Tools installs registry keys, I think it just updates the PATH and maybe some other envvars?  It's basically the pure-cli version of Visual Studio designed for CI builds and so forth.

**Comment by ProfFan** [comment]
This version is not building for me on macOS High Sierra. The error is:
```
ld: warning: ignoring file libluajit.a, file was built for archive which is not the architecture being linked (x86_64): libluajit.a
Undefined symbols for architecture x86_64:
  "_luaJIT_version_2_0_5", referenced from:
      _pmain in luajit.o
  "_luaL_callmeta", referenced from:
      _traceback in luajit.o
...
```

**Comment by elliottslaughter** [comment]
@ProfFan Where did you get your LLVM? I'm also on 10.13.6, and I've had trouble building with certain binaries (though I can't remember ever seeing that exact message), but so far no trouble whenever I build LLVM from source.

**Comment by ProfFan** [comment]
@elliottslaughter  I think it is not a problem with LLVM, as the failure is at the LuaJIT building.

**Comment by elliottslaughter** [comment]
@ProfFan Could you upload the full log somewhere? Might also be good to start from a fresh clone in case there is any residue left over.

**Comment by aiverson** [comment]
I tested the binary release build on both Windows 10 and Arch Linux.

Under windows 10, I see the same symptom as mentioned previously with the failure to find the specified registry entry. I see the same set of failing tests with the addition of rd.t. However, all the cuda tests passed.

Under Arch Linux, I initially see a failure due to being unable to load libtinfo.so.5 because Arch Linux provides libtinfo.so.6. After putting a symlink to libtinfo.so.6 on the LD_PATH for Terra, Terra runs but writes to the terminal an error message stating `libtinfo.so.5: no version information available (required by /.../terra-Linux-x86_64-2e2032e/bin/terra)`. The test report indicates that only dylib.t failed, with 522 tests passing and one failed. Cuda was enabled.

Testing darkroom from latest version on github produces the following error message
```
src/terralib.lua:774: bad argument #6 to 'addvalue' (string expected, got nil)
stack traceback:
        [C]: in function 'addvalue'
        src/terralib.lua:774: in function 'jitvalue'
        src/terralib.lua:526: in function 'compile'
        src/terralib.lua:532: in function 'getpointer'
        src/terralib.lua:540: in function 'makeIm'
        /home/aiverson/utils/darkroom/extras/darkroomSimple.t:75: in function 'load'
        test.t:57: in main chunk
        switch.lua:1: in main chunk
make: *** [makefile:15: out/switch.lua.bmp] Error 1
```

On Ubuntu 16.04, 523 tests pass, 0 failures.

Darkroom produces the same error under Ubuntu as under ArchLinux

**Comment by ProfFan** [comment]
@elliottslaughter Finally found the problem. I accidentally linked `binutils` which gives me a rogue `ar` utility. Now it compiles flawlessly.

**Comment by ProfFan** [comment]
@elliottslaughter Tested the test suite & Opt with CUDA on macOS, so far no problem :)

Darkroom produces the same error as @aiverson 's, probably we can ignore Darkroom for now?

Also, are there any other important downstream projects?

**Comment by elliottslaughter** [comment]
@jameshegarty Would you be interested in helping to test Darkroom against the new beta release of Terra? See above for errors we're seeing. ^^

**Comment by jameshegarty** [comment]
I dno if it makes sense to test Darkroom, since I'm not really maintaining that code (I'm not even sure if it works with the last public release of terra from a few years ago). But we should try it with Rigel (https://github.com/jameshegarty/rigel).

you can just do:
cd rigel/examples
make terra

I will try running this myself ASAP

**Comment by Clyybber** [comment]
@viluon Here is the link to darkroom: https://github.com/jameshegarty/darkroom
 and Opt: https://github.com/niessner/Opt

**Comment by elliottslaughter** [comment]
@jameshegarty I got Rigel to pass with Terra. One thing I noticed is that even in a Terra build, Rigel still expects LuaJIT to be on PATH, which currently means fishing it out of the location where Terra is installed because whatever Rigel is doing with LuaJIT isn't compatible with the Terra executable. If it's not too much trouble, it might be nice to make this work with the Terra binary itself because in the future we may want to change where and how Terra's internal LuaJIT is installed.

**Comment by viluon** [comment]
@Clyybber thanks for the links. Unfortunately, coursework has been very demanding these past weeks, and I still haven't been able to help with testing Terra. I may find some extra time over the holidays, but no promises :confused:

**Comment by elliottslaughter** [comment]
Just FYI, the author of darkroom responded earlier in the thread to say that it's probably not worth testing. So I think Opt or Rigel are the only ones that aren't tested on all platforms yet.

**Comment by jameshegarty** [comment]
@elliottslaughter the default makefile uses luajit b/c I don't want people to be required to install terra if they don't need that functionality. Running 'make terra' will run the terra tests only. I guess some of the luajit tests don't work in terra b/c it includes the code that checks for undeclared globals (so this is my bug). I just ran the terra stuff on my ubuntu machine and it looks good, so I approve this release!

Thanks for continuing to support this project!

**Comment by ProfFan** [comment]
> @elliottslaughter the default makefile uses luajit b/c I don't want people to be required to install terra if they don't need that functionality. Running 'make terra' will run the terra tests only. I guess some of the luajit tests don't work in terra b/c it includes the code that checks for undeclared globals (so this is my bug). I just ran the terra stuff on my ubuntu machine and it looks good, so I approve this release!
> 
> Thanks for continuing to support this project!

Just adding my two cents that Lua tests can fail if you have things like `luarocks` in your LUA_PATH. On my machine `unset LUA_PATH` usually fixes these fails.

**Comment by Mx7f** [comment]
Still digging into this, but as a heads up, I'm getting ~12x slowdown for cuda kernels using this release (and cuda 9.2) for Opt. Trying to figure out why...

**Comment by elliottslaughter** [comment]
@jameshegarty Sure, I get why you'd want it to work with a stock LuaJIT. My point was that the there must be some options of LuaJIT that you're using that aren't supported by Terra, because the following doesn't work:

```
mkdir bin
ln -s ../release/bin/terra bin/luajit
export PATH=$PATH:$PWD/bin
```

It's not really such a huge deal, it just means that you have to use Rigel with a from-source build of Terra, because we don't currently install the LuaJIT binary (and probably wouldn't want to), so it has to be fished out of the build directory where it gets placed at the moment.

**Comment by jameshegarty** [comment]
@elliottslaughter The only issue I had doing that on my machine is that the TERRA_PATH wasn't set  in the script for the luajit branches ('rigelLuajit' script)... basically, it auto-detected that it was Terra, tried to load the terra sources, but it wasn't in the path. Let me know if you had other issues than this. I will try to remember to check in a fix the next time I commit some code. Thx!

**Comment by Qix-** [comment]
How would I go about building a Windows application with Cygwin without VS installed? I have clang et al - shouldn't that be enough?

**Comment by elliottslaughter** [comment]
I haven't personally tried cygwin, but I think if you want to try, just open up the cygwin shell and use the traditional Makefile (or CMake).

Having said that, I have no idea if that's going to work, as there maybe Windows specific code that assumes VS and/or headers available only through VS. You might find yourself needing to add some cygwin ifdefs into the code to get it to work.

Similarly, I don't think the VS-based Terra builds can really reasonably work without VS installed, since they depend on headers that are included in the VS installation. Maybe I'm wrong about that and the dependency isn't that strict, but I'd set my expectations low if you're going to try hacking it to work without VS.

**Comment by Qix-** [comment]
Which VS headers? Do you mean the system headers? Those are included with the redistributables.

Unless Terra uses MSVC internals somehow?

**Comment by elliottslaughter** [comment]
https://github.com/zdevito/terra/blob/master/src/terralib.lua#L4062-L4086

If there's a way to do that without a VS installation, I'd appreciate a PR!

**Comment by ProfFan** [comment]
Just want to mention that I tested `Opt` against latest `master` of **Terra**, with dynamic linkage of LLVM. It works like a charm :)

**Comment by memophen** [comment]
How to install Release 1.0.0-beta1 for Windows? I couldn't find any instructions on that, so I simply unpacked terra-Windows-x86_64-2e2032e.zip and tried to play with it. Got errors like:

```
ERROR: The system was unable to find the specified registry key or value.

<buffer>:1:10: fatal error: 'stdio.h' file not found
#include "stdio.h"
         ^~~~~~~~~
compilation of included c code failed
```

All messages seem to indicate that I have overlooked one or more dependencies. VS? Clang? LLVM? Environment variables? What exactly is needed to get an operational configuration on Win10?

And once I have succeeded to create a Terra executable, will that still be dependent on other software than the bare OS?

**Comment by capr** [comment]
@memophen The headers for the CRT come with VS. Terra looks for the location of that in the registry which is why you get that error. You can also use mingw64's headers if you set the location manually by overwriting `terra.systemincludes`. Once you get an exe there won't be any dependencies (compiled terra code doesn't have a runtime).

**Comment by memophen** [comment]
@capr I tried both. First installed **Visual Studio Community 2019** (16.1.5). Does not have the header files I need. Besides that, judging from _terralib.lua_, version 12.0 is expected. This won't help me further.

Then **mingw-w64**. How to overwrite `terra.systemincludes`? The only thing I could think of is setting the environment variable CUDA_PATH. It makes me feel a Dr. Moreau, but it has a positive effect. Instead of _452 tests passed. 71 tests failed._ I get _493 tests passed. 30 tests failed._ What's still wrong, is shown by running the hello script from http://terralang.org/:
```
ERROR: The system was unable to find the specified registry key or value.
ERROR: The system was unable to find the specified registry key or value.
Hello, Lua!
Hello, Terra!
definition      {int32,&&int8} -> int32

define i32 @"$hello"(i32, i8**) {
entry:
  %puts = tail call i32 @puts(i8* getelementptr inbounds ([14 x i8], [14 x i8]* @str, i64 0, i64 0))
  ret i32 0
}
llvm: program not executable

stack traceback:
        [C]: in function 'saveobj'
        C:\projects\terra\src\terralib.lua:4034: in function 'saveobj'
        hello.t:38: in main chunk
```
The first two error messages seem to be harmless. `hello:disas()` doesn't give the same outcome as promised by the script. But the message about LLVM is really worrying.

**Comment by capr** [comment]
@memophen look at https://github.com/luapower/terra/blob/master/terralib_luapower.lua for how to set systemincludes

disas() doesn't give assembler code on Windows only LLVM IR (works on Linux though)

saveobj() detects binary type based on file extension IIRC so try it with 'helloterra.exe'

do you have stdio.h on your hard drive? find it manually then modify terralib.lua to point to it, it doesn't have to be VS 12

**Comment by memophen** [comment]
@capr (1) The CUDA_PATH method did the trick, no complaints about _stdio.h_ anymore. Setting `terra.systemincludes` the way you indicate does not work for me. Reducing it to its preliminary essentials:
```
local ffi  = require 'ffi'
local List = require 'asdl'.List

print('ffi.os', ffi.os)
terra.systemincludes = List()
print 'So far'
```
The script stops before executing:
```
ERROR: The system was unable to find the specified registry key or value.
ERROR: The system was unable to find the specified registry key or value.
terralib_luapower--MINIMALIZED.t:5: '<name>' expected near '.'
```
`ffi.os` is 'Windows' indeed, by the way.

(2) I can accept `disas()` as is.

(3) Adding the `.exe` extension doesn't make any difference.

(4) There is no _terralib.lua_ in the build (_terra-Windows-x86_64-2e2032e.zip_). My assumption of a reference to v12.0 was based on the source I downloaded separately (_terra-release-1.0.0-beta1.zip_).

**Comment by PyryM** [comment]
`llvm: program not executable`

This very helpful error message is caused when llvm can't find the linker (link.exe on Windows); a recent pull (https://github.com/zdevito/terra/pull/400) partially fixed this, as long as you run terra from the 'Developer Command Prompt' or 'x64 Native Tools Command Prompt' which set the right environment variables.

**Comment by elliottslaughter** [comment]
@PyryM can you try again on the latest master? We just merged #411 which should make this a lot better.

**Comment by blackhole12** [comment]
After going through this thread, I am alarmed at the amount of development being done by developers who simply do not use Windows, don't know how it works, and in some cases seem to aggressively not care, so I want to make a few things clear:

1) You **absolutely must** use the Windows SDK to build anything on Windows. Even clang finds the windows SDK and builds against it when building things for windows. The Windows SDK contains `kernel32.lib` which is what _all executable binaries on the entire operating system must link to_. 

    Now, this doesn't always require that the Windows SDK is actually _present_ on your machine. Every compiler for any language in existence that builds things on windows actually includes a part of the Windows SDK inside of itself. What happens is that languages like Rust and Go and Lua all have their own _runtimes_. These runtimes are always built against the Windows SDK using Visual Studio. This is exactly what LuaJIT does, and it's why you can drag it around to other machines that don't have Windows SDK installed and it will still work - the internal runtime was already linked against the Windows SDK and all the relevant parts of the SDK now exist inside the LuaJIT runtime itself.

    This is where we run into trouble. "All relevant parts" of the Windows SDK makes sense for a language like Lua, or Go, or Rust, who all have their own standard libraries that languages use. These languages do not, under normal circumstances, link directly to C headers, which means everything they need inside the Windows SDK is contained inside their own runtimes. If you *do* link directly against C headers, suddenly there is no "relevant part" of the Windows SDK anymore. You need **all of it**. The whole thing. Because Terra supports compiling arbitrary C code, it requires _the entire Windows SDK_, and by extension, the Visual Studio C runtime. 

2) While it may be possible to find a substitute C runtime to avoid requiring Visual Studio, this would require compiling both LLVM and LuaJIT against this same substitute C runtime. It is possible to _statically_ compile the Visual Studio C Runtime, which will help make `terra.exe` itself portable without the hack of copying `msvcp140.dll` (which you are definitely not supposed to be doing). This same technique can be used to make executables Terra compiles portable, by statically linking the C runtime.

    However, the runtime must still be present, and once again, we can't compile our own runtime that wraps around it, because Terra supports compiling arbitrary C code, which implies requiring _the entire visual studio runtime_. I have done some investigation and it _may_ actually be possible to drop the vcruntime requirement under certain conditions, but [this only works on Windows 10](https://docs.microsoft.com/en-us/cpp/porting/upgrade-your-code-to-the-universal-crt?view=vs-2019), which separated the C runtime into a windows component. Earlier versions do not. This, of course, is ignoring the fact that we still have to compile LuaJIT, which currently demands the Visual Studio be present _anyway_, unless it is precompiled, and the fact that we rely on `link.exe`, which would have to be substituted with LLD.

3) Because of all this, not only do you _have_ to query the registry to find the Windows SDK and Visual Studio on the host computer, you _have_ to invoke a bunch of insane COM calls, all of which is [officially documented by Microsoft](https://github.com/microsoft/vs-setup-samples) as being The Correct Way of doing things.

4) Using `cygwin` or `mingw` are poor solutions that often don't work correctly, because they attempt to patch the actual C runtime with their own so they can try to pretend Windows is Linux. Windows is not Linux and this is almost never a reliable way of building anything. The Windows SDK being installed is non-negotiable. This is always going to be required. If we don't want to require Visual Studio, we should investigate if Terra can avoid using the vcruntime and depend only on the universal C runtime, but this might not be possible.

As a side-note, **Terra executables are not portable**. They dynamically link to the Visual Studio runtime, which requires the user install the corresponding Visual Studio Redistributable. This can be fixed if the entire LLVM + LuaJIT + Terra toolchain is changed to statically compile the runtime instead. If people are interesting in attempting to fix any of these situations under windows, we should file issues to track each one.

**Comment by capr** [comment]
Just a couple of notes:

What you refer to as the C runtime is actually the C++ runtime (msvcp*.dll). The C runtime is msvcrt.dll and it's a Windows built-in since forever. You can safely link against that without redistribution issues but that's only for C programs. C++ programs must link msvcp statically or tell the user to download it from ms website since you're not licensed to include it yourself.

About mingw not working correctly, the entire luapower collection (including luajit, terra, llvm and binaries built with terra) is built on mingw64 since the beginning and I never had a bug from that. Luapower's terra.dll btw _is_ portable, you can check it out here: https://github.com/luapower/terra/tree/master/bin

About the whole compiler detection thing, I personally wouldn't have done any of that, just add mention in the docs that you need to set the include paths of your CRT (be that VC or mingw depending on how you've built terra) if you want to use C headers from Terra. Every programmer would understand.

**Comment by blackhole12** [comment]
There are legends about mingw being poorly behaved in other projects. If it happened to work for you, congratulations, but I will never recommend it to anyone doing windows development.

I double checked and it looks like terra is linking against the C library, not the C++ one, so the executables being produced are actually portable, it is only terra itself that needs to be statically linked so we stop copying `msvcp140.dll` around. However, `clang` prefers to link against `libcmt` instead of `msvcrt`, so I think terra should prefer that as well. Unfortunately, I'm not willing to make this change until we can figure out why we can't compile `stdio.h` correctly.

**Comment by elliottslaughter** [comment]
I'd be fine with statically linking `libcmt` on Windows, and at least for certain LLVM versions we've already got builds that do that (see e.g. [here](https://github.com/elliottslaughter/llvm-package-windows/releases/tag/clang-3.8.1-nvptx)). Right now the main limiting factor to getting more is that the builds time out on AppVeyor.

On Linux I think the holy build box approach probably makes more sense (i.e. dynamically link an old glibc for maximum compatibility, and statically link everything else), but if people want to convince me otherwise, by all mean do so.

I think we're not going to be able to get away without needing a full C compiler infrastructure at least at the point where Terra is being used to compile something. Since as @blackhole12 noted, we can compile arbitrary C code, and I consider this a feature not a bug (for exactly the reason why [Dragon FFI](https://github.com/aguinet/dragonffi) exists when CFFI was already a thing). But if there are things we can do to improve the portability of Terra (so you don't need the same compiler/distro when using Terra to compile something as when you built it) then I'm all ears.

**Comment by blackhole12** [comment]
If Terra ever actually gets [a standard library](https://github.com/aiverson/std), it would be possible to build a "Terra runtime" which then contains whatever parts of the C standard library that the Terra standard library wraps around. This would allow you to compile terra code that only depends on the Terra standard library with no external C code without needing the Windows SDK or Visual Studio. This would still require switching to the `LLD` linker, because `link.exe` is only shipped with Visual Studio.

**Comment by elliottslaughter** [comment]
I forgot to add to my last comment: I'd be happy to have better MinGW support in Terra, and I think it could live alongside the existing MSVC support. But (as with all things in the project) it will have to come from someone who uses that platform on a regular basis and is willing to put in the time to make the improvements. There's a reason why the MSVC support has been advancing so rapidly recently....

**Comment by elliottslaughter** [comment]
Enough has changed recently that I'm planning to cut another beta release. Please let me know if there are any issues that should block that. (I consider documentation issues blockers for 1.0 but not for the next beta.)

**Comment by ErikMcClure** [comment]
I was originally going to suggest making another release once switch statements were added, but that has apparently devolved into a debate about whether it should even exist, so that's not going to happen.

I would consider trying to rebuild LLVM by statically linking the C++ runtime instead of shipping the dynamic library, but I haven't made any progress with that.

**Comment by elliottslaughter** [comment]
I do want to get switch or jump tables into a release, but I think it's worth taking the time to do them right.

I'm happy to do releases more frequently, assuming there is something worth releasing. So if we get switches shortly after this beta we can just do another one.

**Comment by ErikMcClure** [comment]
I don't think there are any really serious blocking issues at the moment, but nobody's actually gone back to check if we've been able to improve the situation in #366, which I believe was partially caused by the include header problem that I fixed. I'm hoping that my fix makes the result more portable, but we'd have to find the people who were having trouble installing terra and ask them to try again.

Of course, on the other hand, it'd be a lot easier to test if they can install terra if we have a beta build for them to test with, so maybe the best course of action is to simply make a second beta release and then use that to run more tests.

**Comment by PyryM** [comment]
I'm happy to test things on Windows if there are binaries available (so more frequent releases are better for me). And I believe the newly-introduced "github actions" (github's own CI/CD) does support Windows hosts, and claims to be free for public repos.

**Comment by elliottslaughter** [comment]
I think you can always get the most recent build off of AppVeyor, e.g. here's yesterday's build: https://ci.appveyor.com/api/buildjobs/3q0q8a9nccb0onxv/artifacts/terra-Windows-x86_64-8c6ccd0.zip

I wouldn't mind considering a more unified CI platform; we've got an issue about it at #355. The main limiter (as always) is someone's time to play around with the options and find something that works better than our current solution.

**Comment by aiverson** [comment]
I'd like to have improved RAII/memory management stuff in for the initial release of 1.0, but I don't think it should block making another beta release.

I think that there should be syntax support for some other things, but they don't need to all get implemented at once.
* let expressions, including using them inside constants when the only statements are variables being declared and initialized to constants
* Some form of switch statement/expression, C-style ints only at minimum, but an ADT Match operation would be great.

**Comment by Mx7f** [comment]
Testing on a Google Compute Engine; clean Ubuntu 18.04 installation. Installed Cuda 10.2; the GPU is a Tesla T4 (which is compute architecture 7.5, which is the latest). The cuda tests all fail with:

```
'sm_75' is not a recognized processor for this target (ignoring processor)
'sm_75' is not a recognized processor for this target (ignoring processor)
'sm_75' is not a recognized processor for this target (ignoring processor)
'sm_75' is not a recognized processor for this target (ignoring processor)
'sm_75' is not a recognized processor for this target (ignoring processor)
'sm_75' is not a recognized processor for this target (ignoring processor)
'sm_75' is not a recognized processor for this target (ignoring processor)
'sm_75' is not a recognized processor for this target (ignoring processor)
'sm_75' is not a recognized processor for this target (ignoring processor)
'sm_75' is not a recognized processor for this target (ignoring processor)
cudahello.t:25: cuModuleLoadData: cuda reported error 218: a PTX JIT compilation failed
```

```
=================
= FAILING tests
=================
cudaagg.t
cudaoffline.t
cudaaggregate.t
cudatex.t
cudaglobal.t
cudashared.t
cudaconst2.t
cudaoo.t
cudatest.t
cudahello.t
cudaprintf.t
cudaatomic.t
=================

511 tests passed. 12 tests failed.
```

I'm guessing the problem is that this GPU's compute capability is higher than the highest supported by whichever version of LLVM produced the binaries, and the proper fix is to query LLVM for the highest supported and clamp the version to that. I'll give it a shot building from source in the coming days.

**Comment by ProfFan** [comment]
Just a side note: I recently upgraded my Mac to macOS Catalina, so I will not be able to test macOS + CUDA anymore as NV does not provide drivers for 10.14+... But anyway the user base is small so I assume that will not hurt too much...

**Comment by elliottslaughter** [comment]
If you have time it would be good to check there are no new issues on Catalina (i.e. relative to #365, which is still outstanding).

**Comment by ErikMcClure** [comment]
Since we have a beta2 now, maybe this should be updated?

**Comment by elliottslaughter** [comment]
Yeah, this issue has become large enough to be unmanageable, I'll regenerate the issue and copy the remaining todos.

**Comment by elliottslaughter** [comment]
New issue is at #439. Please move all new discussion there.

**Comment by elliottslaughter** [comment]
> @Mx7f wrote:
>
> Still digging into this, but as a heads up, I'm getting ~12x slowdown for cuda kernels using this release (and cuda 9.2) for Opt. Trying to figure out why...

Just wanted to follow up on this. Since the changes in https://github.com/terralang/terra/issues/471#issuecomment-1095468660 I'm getting equivalent performance with LLVM 13. It may be worth trying this out on Opt, if this is still something you care about.
