### ISSUE TITLE
Please test 1.0.0-beta2

### ISSUE THREAD

**Issue by elliottslaughter** [terralang/terra#439]
We have a new beta towards our 1.0.0 release. This probably won't be the last, since there are still things we want to do. But anyway, progress!

See the release here: https://github.com/terralang/terra/releases/tag/release-1.0.0-beta2 (this includes binaries and a summary of changes since the last beta)

Like last time, let's try to make sure the release actually works everywhere we expect:

Test/OS| Linux | OSX | Windows
--|--|--|--
Test Suite w/o CUDA| :white_check_mark: (Travis) | :white_check_mark: (Travis) | :white_check_mark: (AppVeyor)
Test Suite with CUDA| | |  
Rigel | |   |  
Opt          |    | |  
Regent | |  | N/A

Other todo items:

 - [ ] #173 (document `label([name])` and `and` for multiple functions)
 - [ ] #154 (document `defer`)
 - [ ] https://github.com/zdevito/terra/issues/323#issuecomment-447613468 (CUDA slowdown)
 - [ ] #333 (document `__for`)
 - [ ]  #366 (portability of Linux binaries)

Optional:

 - [ ] #388 (holy build box)

**Comment by PyryM** [comment]
Would it be possible to get binaries compiled against LLVM 8+? LLVM 8 in particular brings the webassembly backend enabled by default, which is something that would be useful to have 'out of the box'.

**Comment by elliottslaughter** [comment]
Sure, is a Ubuntu 16.04 build ok? CUDA 9.2?

**Comment by swift2plunder** [comment]
1.0.0-beta2 will run on Ubuntu >= 20.4, but requires "apt install libtinfo5"

**Comment by elliottslaughter** [comment]
Superseded by #492.
