### ISSUE TITLE
Please test 1.0.0-beta3

### ISSUE THREAD

**Issue by elliottslaughter** [terralang/terra#492]
We once again have a new release. Please help us test as we continue to widdle down the issues for 1.0

See the release here: https://github.com/terralang/terra/releases/tag/release-1.0.0-beta3 (this includes binaries and a summary of changes since the last beta)

Like last time, let's try to make sure the release actually works everywhere we expect:

Test/OS| Linux | OSX | Windows
--|--|--|--
Test Suite w/o CUDA| :white_check_mark: (GitHub Actions) | :white_check_mark: (GitHub Actions) | :white_check_mark: (AppVeyor)
Test Suite with CUDA| | |  
Rigel | |   |  
Opt          |    | |  
Regent | |  | N/A

Other todo items:

 - [x] #446
 - [x] #173 (document `label([name])` and `and` for multiple functions)
 - [x] #154 (document `defer`)
 - [ ] https://github.com/zdevito/terra/issues/323#issuecomment-447613468 (CUDA slowdown)
 - [x] #333 (document `__for`)
 - [x]  #366 (portability of Linux binaries)
 - [x] sync doc changes to README
 - [x] update CUDA in binary builds
 - [x] update LLVM in binary builds
 - [x] move Windows build to Github Actions
 - [x] update CHANGES.txt

Optional:

 - [ ] #388 (holy build box)

**Comment by elliottslaughter** [comment]
I believe I've resolved all of the major outstanding issues with this release. I'll be kicking off beta4 as soon as CI passes.

**Comment by elliottslaughter** [comment]
beta4 is now out, moving discussion to #542 .
